global:
  scrape_interval: 15s  # Scrape every 15 seconds

scrape_configs:
  - job_name: 'bookappbackend'
    static_configs:
      - targets: ['book-app-backend:$SPRING_DOCKER_PORT']

  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
